/*
 * Copyright Contributors to the Malloy project
 * SPDX-License-Identifier: MIT
 */

import {DuckDBInstance} from '@duckdb/node-api';
import {readdirSync, writeFileSync} from 'fs';
import {fileURLToPath} from 'url';
import * as path from 'path';

const here = path.dirname(fileURLToPath(import.meta.url));
const PARQUET_DIR = path.resolve(here, '../data/malloytest-parquet');
const OUT_PATH = path.resolve(here, 'malloytest-redshift.sql');

function mapType(t) {
  const up = t.toUpperCase();
  if (up.includes('STRUCT(') || up.endsWith('[]')) return 'SUPER';
  if (up === 'BIGINT') return 'BIGINT';
  if (up === 'INTEGER' || up === 'INT' || up === 'INT32') return 'INTEGER';
  if (up === 'DOUBLE' || up === 'FLOAT' || up === 'REAL')
    return 'DOUBLE PRECISION';
  if (up.startsWith('DECIMAL')) return up;
  if (up === 'VARCHAR' || up === 'STRING' || up === 'TEXT')
    return 'VARCHAR(65535)';
  if (up === 'DATE') return 'DATE';
  if (up === 'TIMESTAMP WITH TIME ZONE' || up === 'TIMESTAMPTZ')
    return 'TIMESTAMPTZ';
  if (up === 'TIMESTAMP') return 'TIMESTAMP';
  if (up === 'BOOLEAN' || up === 'BOOL') return 'BOOLEAN';
  return 'VARCHAR(65535)';
}

const inst = await DuckDBInstance.create(':memory:');
const conn = await inst.connect();
const tables = readdirSync(PARQUET_DIR)
  .filter(f => f.endsWith('.parquet'))
  .map(f => f.replace('.parquet', ''))
  .sort();

const out = [];
out.push(
  '-- Generated by `node test/redshift/gen_ddl.mjs`. Do not edit by hand.'
);
out.push('CREATE SCHEMA IF NOT EXISTS malloytest;');
out.push('');
for (const t of tables) {
  const r = await conn.run(
    `DESCRIBE SELECT * FROM read_parquet('${PARQUET_DIR}/${t}.parquet')`
  );
  const rows = await r.getRowObjects();
  const cols = rows.map(
    row => `  "${row.column_name}" ${mapType(String(row.column_type))}`
  );
  out.push(`DROP TABLE IF EXISTS malloytest.${t};`);
  out.push(`CREATE TABLE malloytest.${t} (`);
  out.push(cols.join(',\n'));
  out.push(');');
  out.push('');
}
writeFileSync(OUT_PATH, out.join('\n') + '\n');
