-- Generated by `node test/redshift/gen_ddl.mjs`. Do not edit by hand.
CREATE SCHEMA IF NOT EXISTS malloytest;

DROP TABLE IF EXISTS malloytest.aircraft;
CREATE TABLE malloytest.aircraft (
  "id" BIGINT,
  "tail_num" VARCHAR(65535),
  "aircraft_serial" VARCHAR(65535),
  "aircraft_model_code" VARCHAR(65535),
  "aircraft_engine_code" VARCHAR(65535),
  "year_built" BIGINT,
  "aircraft_type_id" BIGINT,
  "aircraft_engine_type_id" BIGINT,
  "registrant_type_id" BIGINT,
  "name" VARCHAR(65535),
  "address1" VARCHAR(65535),
  "address2" VARCHAR(65535),
  "city" VARCHAR(65535),
  "state" VARCHAR(65535),
  "zip" VARCHAR(65535),
  "region" VARCHAR(65535),
  "county" VARCHAR(65535),
  "country" VARCHAR(65535),
  "certification" VARCHAR(65535),
  "status_code" VARCHAR(65535),
  "mode_s_code" VARCHAR(65535),
  "fract_owner" VARCHAR(65535),
  "last_action_date" DATE,
  "cert_issue_date" DATE,
  "air_worth_date" DATE
);

DROP TABLE IF EXISTS malloytest.aircraft_models;
CREATE TABLE malloytest.aircraft_models (
  "aircraft_model_code" VARCHAR(65535),
  "manufacturer" VARCHAR(65535),
  "model" VARCHAR(65535),
  "aircraft_type_id" BIGINT,
  "aircraft_engine_type_id" BIGINT,
  "aircraft_category_id" BIGINT,
  "amateur" BIGINT,
  "engines" BIGINT,
  "seats" BIGINT,
  "weight" BIGINT,
  "speed" BIGINT
);

DROP TABLE IF EXISTS malloytest.airports;
CREATE TABLE malloytest.airports (
  "id" BIGINT,
  "code" VARCHAR(65535),
  "site_number" VARCHAR(65535),
  "fac_type" VARCHAR(65535),
  "fac_use" VARCHAR(65535),
  "faa_region" VARCHAR(65535),
  "faa_dist" VARCHAR(65535),
  "city" VARCHAR(65535),
  "county" VARCHAR(65535),
  "state" VARCHAR(65535),
  "full_name" VARCHAR(65535),
  "own_type" VARCHAR(65535),
  "longitude" DOUBLE PRECISION,
  "latitude" DOUBLE PRECISION,
  "elevation" BIGINT,
  "aero_cht" VARCHAR(65535),
  "cbd_dist" BIGINT,
  "cbd_dir" VARCHAR(65535),
  "act_date" VARCHAR(65535),
  "cert" VARCHAR(65535),
  "fed_agree" VARCHAR(65535),
  "cust_intl" VARCHAR(65535),
  "c_ldg_rts" VARCHAR(65535),
  "joint_use" VARCHAR(65535),
  "mil_rts" VARCHAR(65535),
  "cntl_twr" VARCHAR(65535),
  "major" VARCHAR(65535)
);

DROP TABLE IF EXISTS malloytest.alltypes;
CREATE TABLE malloytest.alltypes (
  "t_int64" BIGINT,
  "t_float64" DOUBLE PRECISION,
  "t_numeric" DECIMAL(38,9),
  "t_bignumeric" DECIMAL(38,9),
  "string" VARCHAR(65535),
  "t_array_string" SUPER,
  "t_array_int64" SUPER,
  "t_bool_true" BOOLEAN,
  "t_bool_false" BOOLEAN,
  "t_bool_null" BOOLEAN,
  "t_date" DATE,
  "t_datetime" TIMESTAMP,
  "t_timestamp" TIMESTAMPTZ
);

DROP TABLE IF EXISTS malloytest.carriers;
CREATE TABLE malloytest.carriers (
  "code" VARCHAR(65535),
  "name" VARCHAR(65535),
  "nickname" VARCHAR(65535)
);

DROP TABLE IF EXISTS malloytest.flights;
CREATE TABLE malloytest.flights (
  "carrier" VARCHAR(65535),
  "origin" VARCHAR(65535),
  "destination" VARCHAR(65535),
  "flight_num" VARCHAR(65535),
  "flight_time" BIGINT,
  "tail_num" VARCHAR(65535),
  "dep_time" TIMESTAMPTZ,
  "arr_time" TIMESTAMPTZ,
  "dep_delay" BIGINT,
  "arr_delay" BIGINT,
  "taxi_out" BIGINT,
  "taxi_in" BIGINT,
  "distance" BIGINT,
  "cancelled" VARCHAR(65535),
  "diverted" VARCHAR(65535),
  "id2" BIGINT
);

DROP TABLE IF EXISTS malloytest.ga_sample;
CREATE TABLE malloytest.ga_sample (
  "visitorId" BIGINT,
  "visitNumber" BIGINT,
  "visitId" BIGINT,
  "visitStartTime" BIGINT,
  "date" VARCHAR(65535),
  "totals" SUPER,
  "trafficSource" SUPER,
  "device" SUPER,
  "geoNetwork" SUPER,
  "customDimensions" SUPER,
  "hits" SUPER,
  "fullVisitorId" VARCHAR(65535),
  "userId" VARCHAR(65535),
  "clientId" VARCHAR(65535),
  "channelGrouping" VARCHAR(65535),
  "socialEngagementType" VARCHAR(65535)
);

DROP TABLE IF EXISTS malloytest.state_facts;
CREATE TABLE malloytest.state_facts (
  "state" VARCHAR(65535),
  "aircraft_count" BIGINT,
  "airport_count" BIGINT,
  "births" BIGINT,
  "popular_name" VARCHAR(65535)
);

