/*
 * Copyright Contributors to the Malloy project
 * SPDX-License-Identifier: MIT
 */
// Writes windows_zones.ts, the Windows time zone name AT TIME ZONE takes for
// each IANA name Malloy accepts, from Unicode's CLDR data: windowsZones.json
// maps IANA names onto Windows zones, and bcp47/timezone.json groups the
// IANA names that are aliases of one zone (Asia/Kolkata beside
// Asia/Calcutta), so every alias of a mapped name is mapped too.
/* eslint-disable no-console */
const {readFileSync, writeFileSync} = require('fs');
const path = require('path');

const windowsZonesFile =
  require.resolve('cldr-core/supplemental/windowsZones.json');
const aliasesFile = require.resolve('cldr-bcp47/bcp47/timezone.json');
const outFile = path.join(__dirname, 'windows_zones.ts');
const cldrVersion = JSON.parse(
  readFileSync(require.resolve('cldr-core/package.json'), 'utf8')
).version;

const zones = JSON.parse(readFileSync(windowsZonesFile, 'utf8')).supplemental
  .windowsZones.mapTimezones;
const aliasGroups = JSON.parse(readFileSync(aliasesFile, 'utf8')).keyword.u.tz;

// The first Windows zone naming an IANA name wins; the 001 (world) row of
// each Windows zone comes first in the data.
const windowsName = new Map();
for (const {mapZone} of zones) {
  for (const iana of mapZone._type.split(' ')) {
    if (!windowsName.has(iana)) {
      windowsName.set(iana, mapZone._other);
    }
  }
}
// Every alias of a mapped name maps to the same Windows zone.
for (const group of Object.values(aliasGroups)) {
  if (typeof group._alias !== 'string') continue;
  const names = group._alias.split(' ');
  const mapped = names.find(n => windowsName.has(n));
  if (mapped === undefined) continue;
  for (const n of names) {
    if (!windowsName.has(n)) {
      windowsName.set(n, windowsName.get(mapped));
    }
  }
}

const lines = [...windowsName.entries()]
  .filter(([iana]) => iana !== '')
  .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  .map(([iana, win]) => `  '${iana}': '${win}',`);

writeFileSync(
  outFile,
  `/*
 * Copyright Contributors to the Malloy project
 * SPDX-License-Identifier: MIT
 */

// GENERATED by build_windows_zones.js from cldr-core ${cldrVersion}; do not edit.
// The IANA name of each time zone, as Malloy spells one, and the Windows name
// AT TIME ZONE takes for it: windowsZones.json plus every bcp47 alias of a
// listed name (Asia/Kolkata beside Asia/Calcutta, Europe/Kyiv beside
// Europe/Kiev); a Windows zone maps from several IANA names.

export const WINDOWS_TIME_ZONES: Record<string, string> = {
${lines.join('\n')}
};
`
);
console.log(
  `build_windows_zones: ${lines.length} zones from cldr-core ${cldrVersion}`
);
