steps:
  - id: nix-quiet-install
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - '-q'
      - nixos/nix:2.15.2
  - id: proxy-install
    name: 'nixos/nix:2.15.2'
    entrypoint: sh
    args:
      - -c
      - 'wget -q -O /workspace/cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 && chmod +x /workspace/cloud_sql_proxy'
    waitFor: ['nix-quiet-install']
  - id: run-script
    name: 'nixos/nix:2.15.2'
    env:
      - 'SNOWFLAKE_ACCOUNT=pt58362-rx92781'
      - 'SNOWFLAKE_WAREHOUSE=LOOKER_WH'
      - 'SNOWFLAKE_DATABASE=MALLOYTEST'
      - 'SNOWFLAKE_SCHEMA=PUBLIC'
    secretEnv: ['SNOWFLAKE_USER', 'SNOWFLAKE_PASSWORD']
    entrypoint: sh
    args:
      - -c
      - ./cloudbuild/build-db/$TRIGGER_NAME.sh
    waitFor: ['proxy-install']
    timeout: '1800s'
timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_32'
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/malloy-303216/secrets/snowflake-user/versions/latest
      env: 'SNOWFLAKE_USER'
    - versionName: projects/malloy-303216/secrets/snowflake-password/versions/latest
      env: 'SNOWFLAKE_PASSWORD'
