import {Client} from 'presto-client';

async function doRun(): Promise<void> {
  console.log('IM DOING STUFF');
  const client = new Client({
    catalog: 'prism',
    schema: 'infrastructure',
    user: 'arreola222',
    ssl: {
      ca: 'CorpCA',
      //cert: '/var/facebook/credentials/arreola/presto/arreola.pem',
      cert: `-----BEGIN CERTIFICATE-----
MIIE7jCCA9agAwIBAgIUJDpBffbhvURxSawsH7Qwc5J2GSowDQYJKoZIhvcNAQEL
BQAwgY8xODA2BgNVBAMML0ZhY2Vib29rIFJvb3RjYW5hbCBDb3JwIEludGVybWVk
aWF0ZSBDQSAyMDIyLTExMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5p
YTETMBEGA1UEBwwKTWVubG8gUGFyazEcMBoGA1UECgwTTWV0YSBQbGF0Zm9ybXMg
SW5jLjAeFw0yNDA2MTIwMDEyMzBaFw0yNDA2MTkwMDEyNDBaMHUxKjAoBgNVBAMM
IXVzZXI6YXJyZW9sYUBDT1JQLlRIRUZBQ0VCT09LLkNPTTEdMBsGA1UECgwUQ09S
UC5USEVGQUNFQk9PSy5DT00xDzANBgNVBAsMBlByZXN0bzEXMBUGCgmSJomT8ixk
AQEMB2FycmVvbGEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQQ92CxgrV1JcNT
32GhctuqHPxW4GZm5JynsZTUcrs7tnIZGMSD/DOc30eijxk+YzNoVGBgfWsm58zi
XoUM1w2Wo4ICJDCCAiAwHQYDVR0OBBYEFDg1l8rJEJ9bXiaK0Qd4ccvTFYTsMIG2
BgNVHSMEga4wgauAFMOnZ7CZgYiLnI9fx+OC7iFxIXFfoX2kezB5MSgwJgYDVQQD
DB9GYWNlYm9vayBSb290Y2FuYWwgQ29ycCBSb290IENBMQswCQYDVQQGEwJVUzET
MBEGA1UECAwKQ2FsaWZvcm5pYTETMBEGA1UEBwwKTWVubG8gUGFyazEWMBQGA1UE
CgwNRmFjZWJvb2sgSW5jLoIUUW+hPJcdZQKAKSzeadvei2AA9AUwOQYDVR0fBDIw
MDAuoCygKoYoaHR0cHM6Ly9tZXRhLnB1YmxpY2tleWluZnJhLmNvbS9jcmwvY29y
cDAYBgsrBgEEAYLAFQICAwQJDAdhcnJlb2xhMBUGCysGAQQBgsAVAgIFBAYMBHVz
ZXIwEwYDVR0lBAwwCgYIKwYBBQUHAwIwDwYJKwYBBAGC2kssBAIFADAJBgNVHRME
AjAAMAsGA1UdDwQEAwIFoDASBgsrBgEEAYLAFQICBAQDDAEyMEEGCysGAQQBgsAV
AgIQBDIMMFVSSTptcmw6Ly9jZXJ0aWZpY2F0ZV9zZXJ2aWNlLmNvcnAvU2VyaWFs
TnVtYmVyczBFBggrBgEFBQcBAQQ5MDcwNQYIKwYBBQUHMAGGKWh0dHBzOi8vbWV0
YS5wdWJsaWNrZXlpbmZyYS5jb20vb2NzcC9jb3JwMA0GCSqGSIb3DQEBCwUAA4IB
AQB2x3q1Jx0SMbHfJeiS/oB9RT6rLkrMfOcB3W4FJiwMtQNOa40g8YR8hd8PNots
0AvmSX2On1fKKlIJigLPVHwCZVaw81Mygo+JAbxIOdDYPHTDyZIFsjL8REDwFviO
u/DTAFmCDs7LNl9idiqKiN8wOfEFXHj7q0dYz6dxlGfoNOT//46RbDz6qI5wNcLe
416vsLcih1TnmjcBsyFJAvJXeNxHdYBKGHD3kYRKiR1hc67kIuY/OttdPDjr+2D3
56QXJH0bgk0xhHTROAT5NV6ED8dKcht1WG+7A7zdo1EB67yxFwZLQEW2KdlBdVhC
MsJNDVyCNkD9AH788JDU4t1x
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIFBjCCA+6gAwIBAgIUUW+hPJcdZQKAKSzeadvei2AA9AUwDQYJKoZIhvcNAQEL
BQAweTEoMCYGA1UEAwwfRmFjZWJvb2sgUm9vdGNhbmFsIENvcnAgUm9vdCBDQTEL
MAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEzARBgNVBAcMCk1lbmxv
IFBhcmsxFjAUBgNVBAoMDUZhY2Vib29rIEluYy4wHhcNMjIxMTE2MjE0NDEwWhcN
MjQxMTE1MjE0NDEwWjCBjzE4MDYGA1UEAwwvRmFjZWJvb2sgUm9vdGNhbmFsIENv
cnAgSW50ZXJtZWRpYXRlIENBIDIwMjItMTExCzAJBgNVBAYTAlVTMRMwEQYDVQQI
DApDYWxpZm9ybmlhMRMwEQYDVQQHDApNZW5sbyBQYXJrMRwwGgYDVQQKDBNNZXRh
IFBsYXRmb3JtcyBJbmMuMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
4k8iWl/n2NuwGndzo3oHxtMVXOyODhSLBV6QcPrx5vQKkxAQOLYQyU809gnKxWIS
NIzwfmxbRLVYIi1HeESxK1O92fup4kGC7TQpqwVsS6JA4yGPm69awY5wh5ft7jwz
dSOwyrBWFK9YuH25wjwKBeKNgRe3Kc53RvviHh/TaE3cDy4dLcx/zphQkdTnuMoU
KZ0wVqrY15+vmU+aqq624gWPn2SIOYYQUhfThWKZs12rhz2DYK187lLSUsqzW/JN
1CZXy5L6sEkgMrNFRTrzWbwSxFM3ifUvjkGp2ebToe1TKDhiV513WF0U7MM56o5C
loKp4PNNHBtQDEbWEGFnXwIDAQABo4IBbTCCAWkwHQYDVR0OBBYEFMOnZ7CZgYiL
nI9fx+OC7iFxIXFfMIG3BgNVHSMEga8wgayAFMHF6rXUzuCKRTaLysin/mQMIfN8
oX2kezB5MSgwJgYDVQQDDB9GYWNlYm9vayBSb290Y2FuYWwgQ29ycCBSb290IENB
MQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTETMBEGA1UEBwwKTWVu
bG8gUGFyazEWMBQGA1UECgwNRmFjZWJvb2sgSW5jLoIVAOz7QSaxTTUV9akth9sG
GsScwwc5MA4GA1UdDwEB/wQEAwIBhjASBgNVHRMBAf8ECDAGAQH/AgEAMEkGA1Ud
HwRCMEAwPqA8oDqGOGh0dHA6Ly93d3cuaW50ZXJuYWxmYi5jb20vaW50ZXJuL3B1
YmxpY2tleWluZnJhL2FybC9jb3JwMB8GCWCGSAGG+EIBDQQSFhBPbmNhbGw6IGNp
YWVfY2FwMA0GCSqGSIb3DQEBCwUAA4IBAQAn0qiGvTCyZ4k4aNaxHAi2PMuTjvqm
PQENlIBU8RCx/nQKJZo7C64Pz242RcjAiOKb7mmSRnTN7a0fhhB5M5la1sTVI8Wy
1cN21MeGV+Km5X5cHGkV5Ve/yzVQkQOSsx2tQaNxd0z/dOENw0AmAVuInvWNY0O2
c4nE+7WtKTuYKBW/ZB0/u0zMUW6PM7P8oKC598Hj26Ig1dPYhWegupE4sVq4P5hC
nnUkAIp4hLoScGAOhdDxcDLytOFPwSZ14maLiaKqc4gq2RY8w+va5jSga7+uF+p+
OYgmeTjyUbSbmlAxd46KUWsjnJRYDpbrZZnhy1RC+e2RvmKIc9eiF+CH
-----END CERTIFICATE-----`,
    },
    //source: 'presto-client-js-test',
    host: 'proxy.presto.fbinfra.net',
    port: 7778,
    timeout: 60000,
  });
  try {
    console.log('running query');
    await client.execute({
      query: 'SELECT * FROM dim_public_tasks limit 1;',
      success: (error, stats, info) => {
        console.log(
          `SUCCESS: error ${JSON.stringify(error)} stats ${JSON.stringify(
            stats
          )} info ${JSON.stringify(info)}`
        );
      },
      error(error) {
        console.log(`ERROR: ${JSON.stringify(error)}`);
      },
    });
  } catch (e) {
    console.log(e);
  }
}

doRun();
