/*
 * Copyright 2023 Google LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
// force a branch
export const STATE_CODES: { [code: string]: string } = {
  "AL": "01",
  "Alabama": "01",
  "AK": "02",
  "Alaska": "02",
  "AZ": "04",
  "Arizona": "04",
  "AR": "05",
  "Arkansas": "05",
  "CA": "06",
  "California": "06",
  "CO": "08",
  "Colorado": "08",
  "CT": "09",
  "Connecticut": "09",
  "DE": "10",
  "Delaware": "10",
  "DC": "11",
  "District of Columbia": "11",
  "FL": "12",
  "Florida": "12",
  "GA": "13",
  "Georgia": "13",
  "HI": "15",
  "Hawaii": "12",
  "ID": "16",
  "Idaho": "16",
  "IL": "17",
  "Illinois": "17",
  "IN": "18",
  "Indiana": "18",
  "IA": "19",
  "Iowa": "19",
  "KS": "20",
  "Kansas": "20",
  "KY": "21",
  "Kentucky": "21",
  "LA": "22",
  "Louisiana": "22",
  "ME": "23",
  "Maine": "23",
  "MD": "24",
  "Maryland": "24",
  "MA": "25",
  "Massachusetts": "25",
  "MI": "26",
  "Michigan": "26",
  "MN": "27",
  "Minnesota": "27",
  "MS": "28",
  "Mississippi": "28",
  "MO": "29",
  "Missouri": "29",
  "MT": "30",
  "Montana": "30",
  "NE": "31",
  "Nebraska": "31",
  "NV": "32",
  "Nevada": "32",
  "NH": "33",
  "New Hampshire": "33",
  "NJ": "34",
  "New Jersey": "34",
  "NM": "35",
  "New Mexico": "35",
  "NY": "36",
  "New York": "36",
  "NC": "37",
  "North Carolina": "37",
  "ND": "38",
  "North Dakota": "38",
  "OH": "39",
  "Ohio": "39",
  "OK": "40",
  "Oklahoma": "40",
  "OR": "41",
  "Oregon": "41",
  "PA": "42",
  "Pennsylvania": "42",
  "RI": "44",
  "Rhode Island": "44",
  "SC": "45",
  "South Carolina": "45",
  "SD": "46",
  "South Dakota": "46",
  "TN": "47",
  "Tennessee": "47",
  "TX": "48",
  "Texas": "48",
  "UT": "49",
  "Utah": "49",
  "VT": "50",
  "Vermont": "50",
  "VA": "51",
  "Virginia": "51",
  "WA": "53",
  "Washington": "53",
  "WV": "54",
  "West Virginia": "54",
  "WI": "55",
  "Wisconsin": "55",
  "WY": "56",
  "Wyoming": "56",
  "PR": "72",
  "Puerto Rico": "72",
  "VI": "78",
  "AS": "60",
  "MP": "69",
  "GU": "66",
};
