/*
 * Copyright Contributors to the Malloy project
 * SPDX-License-Identifier: MIT
 */

import type {
  AnnotationsDef,
  FieldDef,
  RefToField,
  TypeDesc,
} from '../../../model/malloy_types';
import type {DynamicSpace} from '../field-space/dynamic-space';
import {ReferenceField} from '../field-space/reference-field';
import {DefinitionList} from '../types/definition-list';

import type {FieldSpace} from '../types/field-space';
import {FieldName} from '../types/field-space';
import type {LookupResult} from '../types/lookup-result';
import {ListOf, MalloyElement} from '../types/malloy-element';
import type {Noteable} from '../types/noteable';
import type {MakeEntry} from '../types/space-entry';
import {ExprIdReference} from '../expressions/expr-id-reference';
import type {FieldDeclarationConstructor} from './field-declaration';
import {
  AggregateFieldDeclaration,
  CalculateFieldDeclaration,
  GroupByFieldDeclaration,
  ProjectFieldDeclaration,
} from './field-declaration';

import {
  typecheckAggregate,
  typecheckCalculate,
  typecheckDeclare,
  typecheckDimension,
  typecheckGroupBy,
  typecheckIndex,
  typecheckMeasure,
  typecheckProject,
} from './typecheck_utils';

export type FieldReferenceConstructor = new (
  names: FieldName[]
) => FieldReference;

export abstract class FieldReference
  extends ListOf<FieldName>
  implements Noteable, MakeEntry
{
  readonly isNoteableObj = true;
  ownAnnotation?: AnnotationsDef;

  constructor(names: FieldName[]) {
    super(names);
  }

  // The `name is path` declaration constructor used to auto-resolve an output
  // name collision for this kind of reference, or undefined if this reference
  // does not produce an output column named for its last path element (e.g.
  // index references, view references). Overridden by the references that do.
  protected autoRenameDeclarationCtor():
    FieldDeclarationConstructor | undefined {
    return undefined;
  }

  makeEntry(fs: DynamicSpace) {
    const refName = this.outputName;
    if (fs.entry(refName) === undefined) {
      // In a QuerySpace, this needs to be able to find the thing to which it refers
      const fromFS = fs.isQueryFieldSpace() ? fs.inputSpace() : fs;
      fs.newEntry(refName, this, new ReferenceField(this, fromFS));
      return;
    }
    // The natural (last-segment) name is taken. A dotted reference can be
    // auto-renamed using its full path; a single-name reference has no prefix
    // to disambiguate with, so it stays a hard error.
    const declCtor = this.autoRenameDeclarationCtor();
    if (declCtor && this.list.length > 1 && fs.isQueryFieldSpace()) {
      this.autoRename(fs, fs.outputSpace().synthesizedNames, declCtor, refName);
      return;
    }
    if (
      fs.isQueryFieldSpace() &&
      fs.outputSpace().synthesizedNames.has(refName)
    ) {
      this.logError(
        'output-name-conflict',
        `Output already has a field named '${refName}', which was ` +
          'auto-generated by renaming an ambiguous reference; name one of the ' +
          "conflicting references explicitly with 'is' to resolve this"
      );
    } else {
      this.logError(
        'output-name-conflict',
        `Output already has a field named '${refName}'`
      );
    }
  }

  // Rewrite `path.to.field` into the equivalent `autoName is path.to.field`
  // declaration — the same AST the user would write to fix it by hand — and
  // let its normal makeEntry produce the (renamed) output field.
  private autoRename(
    fs: DynamicSpace,
    synthesizedNames: Set<string>,
    declCtor: FieldDeclarationConstructor,
    refName: string
  ): void {
    // `path.join('_')`, then `_2`, `_3`, ... until free. The synthetic name
    // yields to whatever is already in the output, so a user-written name wins.
    const base = this.path.join('_');
    let autoName = base;
    let n = 2;
    while (fs.entry(autoName) !== undefined) {
      autoName = `${base}_${n++}`;
    }
    synthesizedNames.add(autoName);
    this.logWarning(
      'output-field-auto-renamed',
      `Output already has a field named '${refName}', so '${this.refString}' ` +
        `was renamed to '${autoName}'. Write '${autoName} is ${this.refString}' ` +
        'to set the name explicitly and silence this warning.'
    );
    const renamedRef = new ExpressionFieldReference(
      this.list.map(n => new FieldName(n.refString))
    );
    const decl = new declCtor(new ExprIdReference(renamedRef), autoName);
    if (this.ownAnnotation) {
      decl.ownAnnotation = this.ownAnnotation;
    }
    // Attach under this reference so the synthetic nodes inherit its location
    // and resolve back to the translator for logging.
    this.has({autoRenamed: decl});
    decl.makeEntry(fs);
  }

  getName(): string {
    return this.nameString;
  }

  get refToField(): RefToField {
    return {
      type: 'fieldref',
      path: this.list.map(n => n.refString),
      at: this.location,
    };
  }

  get refString(): string {
    return this.path.join('.');
  }

  get path(): string[] {
    return this.list.map(n => n.refString);
  }

  get outputName(): string {
    const last = this.list[this.list.length - 1];
    return last.refString;
  }

  get sourceString(): string | undefined {
    if (this.list.length > 1) {
      return this.list
        .slice(0, -1)
        .map(n => n.refString)
        .join('.');
    }
    return undefined;
  }

  get nameString(): string {
    return this.list[this.list.length - 1].refString;
  }

  abstract typecheck(type: TypeDesc): void;

  getField(fs: FieldSpace): LookupResult {
    const result = fs.lookup(this.list);

    if (result.found) {
      const actualType = result.found.typeDesc();
      this.typecheck(actualType);
    }

    return result;
  }
}

export class AcceptExceptFieldReference extends FieldReference {
  elementType = 'acceptExceptFieldReference';
  // Nothing to typecheck here
  typecheck() {
    return;
  }
}

export class AccessModifierFieldReference extends FieldReference {
  elementType = 'accessModifierFieldReference';
  // Nothing to typecheck here
  typecheck() {
    return;
  }
}

export class ExpressionFieldReference extends FieldReference {
  elementType = 'expressionFieldReference';
  // We assume that the outer expression will typecheck this
  typecheck() {
    return;
  }
}

export class RefineFromFieldReference extends FieldReference {
  elementType = 'refineFromFieldReference';
  // Already typechecked, because it comes from an already-compiled view
  typecheck() {
    return;
  }
}

export class PartitionByFieldReference extends FieldReference {
  elementType = 'partitionByFieldReference';
  // We assume that the partition by expression will typecheck this
  typecheck() {
    return;
  }
}

export class GroupedByReference extends FieldReference {
  elementType = 'groupedByReference';
  typecheck() {
    return;
  }
}

export class ParameterFieldReference extends FieldReference {
  elementType = 'parameterFieldReference';
  // The invocation of the argument will typecheck this
  typecheck() {
    return;
  }
}

export class DrillFieldReference extends FieldReference {
  elementType = 'drillFieldReference';
  // This is typechecked in the drill statement
  typecheck() {
    return;
  }
}

export class CalculateFieldReference extends FieldReference {
  elementType = 'calculateFieldReference';
  protected autoRenameDeclarationCtor() {
    return CalculateFieldDeclaration;
  }
  typecheck(type: TypeDesc) {
    typecheckCalculate(type, this);
  }
}

export class IndexFieldReference extends FieldReference {
  elementType = 'indexFieldReference';
  typecheck(type: TypeDesc) {
    typecheckIndex(type, this);
  }

  // Index entries are expected to be unique on path
  static indexOutputName(path: string[]): string {
    return path.map(pe => encodeURIComponent(pe)).join('/');
  }

  get outputName(): string {
    return IndexFieldReference.indexOutputName(this.path);
  }
}

export class AggregateFieldReference extends FieldReference {
  elementType = 'aggregateFieldReference';
  protected autoRenameDeclarationCtor() {
    return AggregateFieldDeclaration;
  }
  typecheck(type: TypeDesc) {
    typecheckAggregate(type, this);
  }
}

export class GroupByFieldReference extends FieldReference {
  elementType = 'groupByFieldReference';
  protected autoRenameDeclarationCtor() {
    return GroupByFieldDeclaration;
  }
  typecheck(type: TypeDesc) {
    typecheckGroupBy(type, this);
  }
}

export class ProjectFieldReference extends FieldReference {
  elementType = 'projectFieldReference';
  protected autoRenameDeclarationCtor() {
    return ProjectFieldDeclaration;
  }
  typecheck(type: TypeDesc) {
    typecheckProject(type, this);
  }
}

export class DeclareFieldReference extends FieldReference {
  elementType = 'declareFieldReference';
  typecheck(type: TypeDesc) {
    typecheckDeclare(type, this);
  }
}

export class MeasureFieldReference extends FieldReference {
  elementType = 'measureFieldReference';
  typecheck(type: TypeDesc) {
    typecheckMeasure(type, this);
  }
}

export class DimensionFieldReference extends FieldReference {
  elementType = 'dimensionFieldReference';
  typecheck(type: TypeDesc) {
    typecheckDimension(type, this);
  }
}

export class ViewOrScalarFieldReference extends FieldReference {
  elementType = 'viewOrScalarFieldReference';
  typecheck(_type: TypeDesc) {}
}

export class WildcardFieldReference extends MalloyElement implements Noteable {
  elementType = 'wildcardFieldReference';
  ownAnnotation?: AnnotationsDef;
  readonly isNoteableObj = true;
  except = new Set<string>();
  constructor(readonly joinPath: FieldReference | undefined) {
    super();
    this.has({joinPath});
  }

  getFieldDef(): FieldDef {
    throw this.internalError('fielddef request from wildcard reference');
  }

  get refString(): string {
    return this.joinPath ? `${this.joinPath.refString}.*` : '*';
  }
}

export type FieldReferenceElement = FieldReference | WildcardFieldReference;

export class FieldReferences extends DefinitionList<FieldReferenceElement> {
  elementType = 'fieldReferenceList';
  constructor(members: FieldReferenceElement[]) {
    super(members);
  }
}
