import * as fs from 'fs';

// eslint-disable-next-line no-console
console.log(`/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
/*
 * Autogenerated.
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/`);

function snakeToCamel(m: string) {
  return m.replace(/_([a-z])/g, g => g[1].toUpperCase());
}

function fixEnum(m: string) {
  return m.replace(/ {2}([A-Za-z])+With/g, '');
}

let allTypes = '';
for (const file of fs.readdirSync('./generated-types')) {
  if (file === 'index.ts') continue;
  const text = fs.readFileSync(`./generated-types/${file}`, 'utf8');
  const lines = text.split('\n');
  const firstTypeLine = lines.findIndex(line => line.startsWith('export'));
  const firstNonTypeLine = lines.findIndex(
    line => line.endsWith('Args;') || line.endsWith('Args {')
  );
  let actualTypes = lines.slice(firstTypeLine, firstNonTypeLine).join('\n');
  actualTypes = actualTypes.replace(
    /export interface I([A-Za-z_]+) {/g,
    'export type $1 = {'
  );
  actualTypes = actualTypes.replace(/([A-Za-z]+)\.I\1/g, '$1');
  actualTypes = actualTypes.replace(/([A-Za-z]+)\.\1/g, '$1');
  actualTypes = actualTypes.replace(/= I/g, '= ');
  actualTypes = actualTypes.replace(/\| I/g, '| ');
  actualTypes = actualTypes.replace(/ {4}/g, '  ');
  actualTypes = actualTypes.replace(/With[A-Za-z_]+/g, snakeToCamel);
  actualTypes = actualTypes.replace(/Json/g, 'JSON');
  actualTypes = actualTypes.replace(/Sql/g, 'SQL');
  actualTypes = actualTypes.replace(
    /enum ([A-Za-z]+)Type {\n( {2}\1With([A-Za-z]+) = "[a-z_]+",?\n)+}/g,
    fixEnum
  );
  actualTypes = actualTypes.replace(
    /__type: ([A-Za-z]+)Type\.\1With/g,
    '__type: $1Type.'
  );
  allTypes += actualTypes + '\n';
}

// eslint-disable-next-line no-console
console.log(allTypes);
