steps:
  - id: nix-quiet-install
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - '-q'
      - nixos/nix:2.15.2
  - id: proxy-install
    name: 'nixos/nix:2.15.2'
    entrypoint: sh
    args:
      - -c
      - 'wget -q -O /workspace/cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.386 && chmod +x /workspace/cloud_sql_proxy'
    waitFor: ['nix-quiet-install']
  - id: run-script
    name: 'nixos/nix:2.15.2'
    env:
      - 'PGHOST=127.0.0.1'
      - 'PGDATABASE=postgres'
      - 'PGUSER=673673622326@cloudbuild'
    entrypoint: sh
    args:
      - -c
      - '(/workspace/cloud_sql_proxy -enable_iam_login -instances=malloy-303216:us-central1:pg-test=tcp:5432 -log_debug_stdout > /dev/null & sleep 2) && (./cloudbuild/build-test/$TRIGGER_NAME.sh)'
    waitFor: ['proxy-install']
    timeout: '1800s'
timeout: '1800s'
options:
  machineType: 'E2_HIGHCPU_8'
