/*
 * Copyright 2023 Google LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

export type {
  Connection,
  ConnectionConfig,
  ConnectionFactory,
  ConnectionParameter,
  ConnectionParameterValue,
  ConnectionConfigSchema,
  FetchSchemaOptions,
  InfoConnection,
  LookupConnection,
  ModelString,
  ModelURL,
  PersistSQLResults,
  PooledConnection,
  QueryString,
  QueryURL,
  TestableConnection,
  StreamingConnection,
  URLReader,
} from './runtime_types';

export type {
  QueryDataRow,
  // Currently needed only by tests
  Fragment,
  // Needed for DB
  StructDef,
  StructRelationship,
  NamedStructDefs,
  MalloyQueryData,
  AtomicFieldType as AtomicFieldTypeInner,
  DateUnit,
  ExtractUnit,
  TimestampUnit,
  TimeFieldType,
  QueryData,
  QueryValue,
  FieldFragment,
  FieldTypeDef,
  Filtered,
  FilterFragment,
  Expr,
  DialectFragment,
  TimeValue,
  // Needed for drills in render
  FilterExpression,
  SQLBlock,
  // Used in Composer Demo
  FieldAtomicDef,
  FieldDef,
  FilteredAliasedName,
  PipeSegment,
  QueryFieldDef,
  TurtleDef,
  SearchValueMapResult,
  SearchIndexResult,
  ModelDef,
  Query,
  QueryRunStats,
  NamedQuery,
  NamedModelObject,
  ExpressionType,
  FunctionDef,
  FunctionOverloadDef,
  FunctionParameterDef,
  ExpressionValueType,
  TypeDesc,
  FieldValueType,
  ExpressionTypeDesc,
  FunctionParamTypeDesc,
  // used in MalloyError.log
  DocumentLocation,
  DocumentRange,
  DocumentPosition,
  Annotation,
  TypecastFragment,
  FieldAtomicTypeDef,
  Sampling,
  Note,
  Pipeline,
  IndexSegment,
  AtomicFieldType,
  ProjectSegment,
  SQLBlockStructDef,
  QueryResult,
  SQLBlockSource,
  TimeLiteralFragment,
  StructRef,
  CompiledQuery,
  FieldUnsupportedDef,
  DocumentReference,
  FieldBooleanDef,
  FieldDateDef,
  ImportLocation,
  FieldJSONDef,
  FieldNumberDef,
  FieldStringDef,
  FieldTimestampDef,
  SQLPhrase,
  Parameter,
  ReduceSegment,
  EvalSpace,
  AggregateFragment,
  UngroupFragment,
  OrderBy,
  By,
  FunctionCallFragment,
  CastType,
  FieldRef,
  JoinRelationship,
  OutputFieldFragment,
  ParameterFragment,
  QuerySegment,
  ResultMetadataDef,
  ResultStructMetadataDef,
  PartialSegment,
  SpreadFragment,
  DivFragment,
  ModelAnnotation,
  SQLExpressionFragment,
} from './model';

export {
  FieldIsIntrinsic,
  isDateUnit,
  isMatrixOperation,
  isOutputFieldFragment,
  isProjectSegment,
  expressionInvolvesAggregate,
  isParameterFragment,
  isPhysical,
  isReduceSegment,
  isQuerySegment,
  isSpreadFragment,
  isSQLExpressionFragment,
  isUngroupFragment,
  isSQLBlockStruct,
  isAggregateFragment,
  isApplyFragment,
  isApplyValue,
  isAsymmetricFragment,
  isDialectFragment,
  isFieldFragment,
  isFilterFragment,
  isFunctionCallFragment,
  isFunctionParameterFragment,
  getPhysicalFields,
  expressionIsAggregate,
  refIsStructDef,
  expressionIsAnalytic,
  isSQLFragment,
  isFilteredAliasedName,
  isAtomicFieldType,
  isFieldTypeDef,
  isExpressionTypeLEQ,
  maxExpressionType,
  maxOfExpressionTypes,
  mergeEvalSpaces,
  isPartialSegment,
  expressionIsCalculation,
  expressionIsScalar,
  mkExpr,
  isTimestampUnit,
  getIdentifier,
  isAtomicField,
  isTurtleDef,
  isSamplingEnable,
  isSamplingPercent,
  isSamplingRows,
  isCastType,
  isValueParameter,
  paramHasValue,
  hasExpression,
  isJoinOn,
  isExtractUnit,
  isTimeFieldType,
  expressionIsUngroupedAggregate,
  isConditionParameter,
  isIndexSegment,
} from './model';
