/*
 * Copyright 2023 Google LLC
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files
 * (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge,
 * publish, distribute, sublicense, and/or sell copies of the Software,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// TODO this should come from Malloy directly, rather than being hard-coded here.
export const RESERVED_WORDS = [
  'accept',
  'aggregate',
  'declare',
  'dimension',
  'except',
  'explore',
  'group_by',
  'having',
  'index',
  'join_cross',
  'join_one',
  'join_many',
  'limit',
  'measure',
  'nest',
  'order_by',
  'primary_key',
  'project',
  'query',
  'rename',
  'sample',
  'source',
  'sql',
  'turduck',
  'top',
  'where',
  'all',
  'as',
  'asc',
  'avg',
  'boolean',
  'by',
  'case',
  'cast',
  'condition',
  'count',
  'date',
  'day',
  'days',
  'desc',
  'distinct',
  'else',
  'end',
  'exclude',
  'false',
  'for',
  'from',
  'from_sql',
  'has',
  'hour',
  'hours',
  'import',
  'is',
  'json',
  'last',
  'max',
  'min',
  'minute',
  'minutes',
  'month',
  'months',
  'not',
  'now',
  'null',
  'number',
  'on',
  'or',
  'pick',
  'quarter',
  'quarters',
  'second',
  'seconds',
  'string',
  'sum',
  'table',
  'then',
  'this',
  'timestamp',
  'to',
  'true',
  'turtle',
  'week',
  'weeks',
  'when',
  'with',
  'year',
  'years',
  'ungrouped',
];
