/*
 * Copyright Contributors to the Malloy project
 * SPDX-License-Identifier: MIT
 */

import {
  TestTranslator,
  errorMessage,
  warningMessage,
  getQueryFieldDef,
} from './test-translator';
import './parse-expects';

/*
 * When a dotted reference's natural (last-segment) output name collides with
 * a name already in the output, it is auto-renamed using its full path
 * (`user.name` -> `user_name`) and a warning suggests the explicit rewrite.
 * The first reference to claim a name keeps it; later colliding dotted
 * references are the ones that move.
 */
describe('output name auto-rename', () => {
  test('dotted reference renames when its natural name is taken', () => {
    expect('run: ab -> { group_by: ai, b.ai }').toLog(
      warningMessage(
        "Output already has a field named 'ai', so 'b.ai' was renamed to " +
          "'b_ai'. Write 'b_ai is b.ai' to set the name explicitly and " +
          'silence this warning.'
      )
    );
  });

  test('renamed field is the full-path expression, original keeps its name', () => {
    const m = new TestTranslator('run: ab -> { group_by: ai, b.ai }');
    const seg = m.getQuery(0)?.pipeline[0];
    expect(seg).toBeDefined();
    expect(getQueryFieldDef(seg!, 'ai').type).toBe('fieldref');
    // `b.ai` became `b_ai is b.ai`, an ordinary number field
    expect(getQueryFieldDef(seg!, 'b_ai').type).toBe('number');
  });

  test('auto-renames in select/project too', () => {
    expect('run: ab -> { select: ai, b.ai }').toLog(
      warningMessage(/'b\.ai' was renamed to 'b_ai'/)
    );
  });

  test('auto-renames an aggregate, referenceable in having', () => {
    expect(
      `run: ab extend { join_one: b2 is ab on astr = b2.astr } -> {
         aggregate: acount, b2.acount
         having: b2_acount > 0
       }`
    ).toLog(warningMessage(/'b2\.acount' was renamed to 'b2_acount'/));
  });

  test('a bare single-name reference cannot be renamed and still errors', () => {
    // `b.ai` claims `ai` first; the bare `ai` has no prefix to disambiguate.
    expect('run: ab -> { group_by: b.ai, ai }').toLog(
      errorMessage("Output already has a field named 'ai'")
    );
  });

  test('two bare references with the same name still error', () => {
    expect('run: ab -> { group_by: ai, ai }').toLog(
      errorMessage("Output already has a field named 'ai'")
    );
  });

  test('synthetic name increments when its first choice is taken', () => {
    // `b_ai is 1` occupies `b_ai`, so `b.ai` (which would also want `b_ai`)
    // increments to `b_ai_2`.
    expect('run: ab -> { group_by: b_ai is 1, ai, b.ai }').toLog(
      warningMessage(/'b\.ai' was renamed to 'b_ai_2'/)
    );
  });

  test('explicit definition landing on a synthetic name is a hard error', () => {
    expect('run: ab -> { group_by: ai, b.ai, b_ai is 2 }').toLog(
      warningMessage(/renamed to 'b_ai'/),
      errorMessage(/auto-generated by renaming an ambiguous reference/)
    );
  });

  test('bare reference landing on a synthetic name is a hard error', () => {
    expect('run: ab -> { group_by: ai, b.ai, b_ai }').toLog(
      warningMessage(/renamed to 'b_ai'/),
      errorMessage(/auto-generated by renaming an ambiguous reference/)
    );
  });
});
