name: 'DB:DuckDB(WASM)'
permissions: {}

on: workflow_call

jobs:
  test-duckdb-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: workspace
      - name: Extract workspace
        run: tar --use-compress-program='zstd -d -T0' -xf workspace.tzst && rm workspace.tzst
      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - name: Test
        run: npm run ci-duckdb-wasm
        env:
          CI: true
