name: 'DB:DuckDB'
permissions: {}

on: workflow_call

jobs:
  test-duckdb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: npm install, build, and test
        run: |
          npm ci --loglevel error
          npm run build
          npm run build-duckdb-db
          npx jest --reporters jest-silent-reporter --reporters summary --config jest.duckdb.config.ts --runInBand
        env:
          CI: true
          MALLOY_DATABASES: duckdb
