name: 'DB:DuckDB'

on: [pull_request, pull_request_target, workflow_call]

jobs:
  test-duckdb:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci --loglevel error
          npm run build
          npm run build-duckdb-db
          npx jest --reporters jest-silent-reporter --reporters summary --config jest.duckdb.config.ts --runInBand
        env:
          CI: true
          MALLOY_DATABASES: duckdb
