name: 'DB:Snowflake'
permissions: {}

on:
  workflow_call:
    secrets:
      SNOWFLAKE_CONNECTION:
        required: true

jobs:
  test-snowflake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: npm install, build, and test
        run: |
          npm ci --loglevel error
          npm run build
          ./scripts/gen-snowflake-auth.sh
          npx jest --reporters jest-silent-reporter --reporters summary --config jest.snowflake.config.ts
        env:
          CI: true
          MALLOY_DATABASES: snowflake
          SNOWFLAKE_CONNECTION: ${{ secrets.SNOWFLAKE_CONNECTION }}
