name: Snowflake DB

on:
  pull_request:
  workflow_call:
    secrets:
      SNOWFLAKE_CONNECTION:
        required: true

jobs:
  test-snowflake:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm ci --loglevel error
          npm run build
          ./scripts/gen-snowflake-auth.sh
          npm run test-silent -- -- test packages/malloy-db-snowflake
        env:
          CI: true
          MALLOY_DATABASES: snowflake
          SNOWFLAKE_CONNECTION: ${{ secrets.SNOWFLAKE_CONNECTION }}
